#!/usr/bin/env ruby
def reload!
  load './application.rb'
  Time.zone = Loghouse::TIME_ZONE
end

def insert
  names = %w[
    timestamp nsec
    string_fields.names string_fields.values
    number_fields.names number_fields.values
    boolean_fields.names boolean_fields.values
    null_fields.names
  ]

  s = CSV.generate do |csv|
    csv << names
    csv << [
      Time.now.utc.strftime('%Y-%m-%d %H:%M:%S'),
      rand(10_000),
      %w[a b c].to_s.gsub(/"/, "'"), %w[1 2 3].shuffle.to_s.gsub(/"/, "'"),
      %w[d e f].to_s.gsub(/"/, "'"), %w[4 5 6].shuffle.map(&:to_i),
      %w[g].to_s.gsub(/"/, "'"), [1],
      ['x'].to_s.gsub(/"/, "'"),
    ]
  end
  puts s

  Clickhouse.connection.insert_rows(:'logs.logs6', csv: s)
end

reload!

Pry.start
