{
 "title": "Loghouse Fluentd",
 "description": "Loghouse fluentd dashboard",
 "tags": [
  "loghouse",
  "fluentd",
  "db"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "node", "label": "Node", "query": "*" },
   { "name": "namespace", "label": "Namespace", "query": "loghouse" },
   { "name": "controller", "label": "Controller", "query": "ds/fluentd" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\n  min by (pod) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Running\"}[$__interval_sx4])\n  ) == 1\n) * 0",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Pending\"}[$__interval_sx4])\n  ) == 1\n) * 1",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Unknown\"}[$__interval_sx4])\n  ) == 1\n) * 2",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Failed\"}[$__interval_sx4])\n  ) == 1\n) * 3",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Succeeded\"}[$__interval_sx4])\n  ) == 1\n) * 4",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\"}\n    * on (pod) group_right()\n    min by (pod) (min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\", pod=~\"$pod\"}[$__interval_sx4]))\n  ) == 0\n) + 5",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods restarts",
   "type": "graph",
   "description": "Количество рестартов подов",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum by (pod) (avg_over_time(kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\", pod=~\"$pod\"}[$__interval_sx4])) \n  * on (pod)\n  sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__interval_sx4]))\n) > 0",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum (\n  sum by (pod) (avg_over_time(kube_controller_pod{namespace=\"$namespace\", controller=\"$controller\", pod=~\"$pod\"}[$__interval_sx4])) \n  * on (pod)\n  sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__interval_sx4]))\n)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Fluentd $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Fluentd Used buffer (Bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_stage_byte_size{namespace=\"$namespace\", host=~\"$pod\", plugin_id=\"load2clickhouse\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Fluentd Used buffer (In chunks)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_status_buffer_queue_length{namespace=\"$namespace\", host=~\"$pod\", plugin_id=\"load2clickhouse\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Fluentd Clickhouse Uploads Fails",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_status_retry_count{namespace=\"$namespace\", host=~\"$pod\", plugin_id=\"load2clickhouse\",}[$__interval_rv])) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Fluentd Rows inserted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_emit_records{namespace=\"$namespace\", host=~\"$pod\", plugin_id=\"load2clickhouse\"}[$__interval_sx4])",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}