{
 "title": "Loghouse Clickhouse",
 "description": "Clickhouse metrics",
 "tags": [
  "clickhouse",
  "db",
  "loghouse"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "loghouse" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(clickhouse_query_total{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_query_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__interval_sx4])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_merge{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }} merge"
    },
    {
     "expr": "rate(clickhouse_merged_rows_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{ pod }} rate"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_read{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "clickhouse_write{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_compressed_read_buffer_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__interval_sx4])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_tcp_connection{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }} tcp"
    },
    {
     "expr": "clickhouse_http_connection{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }} http"
    },
    {
     "expr": "clickhouse_interserver_connection",
     "legendFormat": "interserver"
    }
   ]
  },
  {
   "title": "Pool Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_background_pool_task{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "clickhouse_memory_tracking{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Cache rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_mark_cache_misses_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "misses {{job}}"
    },
    {
     "expr": "rate(clickhouse_mark_cache_hits_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "hits {{job}}"
    }
   ]
  }
 ]
}